<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="ProyectoBD2U3.FRONTEND.frmLibros" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Libros</title>
    <script type="text/javascript">
        //AQUI COLOCAR CODIGO JAVASCRIPT
    </script>
    </head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
    
    <p>
        <asp:GridView ID="gvLibros" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="gvLibros_RowDeleting" OnRowEditing="gvLibros_RowEditing" OnRowDataBound="gvLibros_RowDataBound">
        </asp:GridView>
        </p>
        <p>
            <asp:Button ID="btnAgregar" runat="server" Text="Agregar" OnClick="btnAgregar_Click" />
        </p>
    </form>
    
    </body>
</html>
