<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="ProyectoBD2U3.FRONTEND.frmLibros" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
   <title>Libros</title>
</head>
<body>
    <div align="center">
        <h2 style="margin-top:0px; padding-top:20px; padding-bottom:20px;background-color: rgb(21,76,121); color: rgb(255,255,255);">Libros</h2>
        <form id="form1" runat="server" > 
            <div class="form-group" >
                <asp:GridView ID="gvLibros" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="gvLibros_RowDeleting" OnRowEditing="gvLibros_RowEditing" OnRowDataBound="gvLibros_RowDataBound" class="container" style="margin: 20px; margin-top:50px; background-color:rgb(233, 140, 100)"> </asp:GridView>
                <asp:Button class="btn btn-primary" ID="btnAgregar" runat="server" Text="Agregar" OnClick="btnAgregar_Click" style="margin: 20px; padding-left: 20px; padding-right: 20px; padding-top: 10px; padding-bottom: 10px; background-color:rgb(74, 92, 128); color:rgb(255,255,255)"/>
            </div>
       </form>
    </div>
    </body>
</html>
